import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'tr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  tr: {
    // Auth
    'auth.login.title': 'Giriş Yap',
    'auth.login.subtitle': 'Şirket hesabınıza giriş yapın',
    'auth.login.email': 'E-posta',
    'auth.login.password': 'Şifre',
    'auth.login.submit': 'Giriş Yap',
    'auth.login.loading': 'Giriş yapılıyor...',
    'auth.login.forgot': 'Şifremi unuttum?',
    'auth.login.noAccount': "Hesabınız yok mu?",
    'auth.login.signup': 'Kayıt ol',
    'auth.login.employeeLogin': 'Çalışan Girişi',
    'auth.login.error': 'Geçersiz e-posta veya şifre',
    'auth.login.errorGeneric': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    
    'auth.employeeLogin.subtitle': 'Çalışan hesabınıza giriş yapın',
    'auth.employeeLogin.username': 'Kullanıcı Adı',
    'auth.employeeLogin.password': 'Şifre',
    'auth.employeeLogin.submit': 'Giriş Yap',
    'auth.employeeLogin.loading': 'Giriş yapılıyor...',
    'auth.employeeLogin.invalid': 'Geçersiz kullanıcı adı veya şifre',
    'auth.employeeLogin.companyLogin': 'Şirket Girişi',
    'auth.employeeLogin.backToCompany': 'Şirket girişine dön',
    
    'auth.signup.title': 'Kayıt Ol',
    'auth.signup.subtitle': 'Şirket hesabınızı oluşturun',
    'auth.signup.companyName': 'Şirket Adı',
    'auth.signup.email': 'E-posta',
    'auth.signup.password': 'Şifre',
    'auth.signup.language': 'Dil',
    'auth.signup.submit': 'Kayıt Ol',
    'auth.signup.loading': 'Hesap oluşturuluyor...',
    'auth.signup.hasAccount': 'Zaten hesabınız var mı?',
    'auth.signup.signin': 'Giriş yap',
    'auth.signup.success': 'Hesabınız başarıyla oluşturuldu! Yönlendiriliyorsunuz...',
    'auth.signup.error': 'Hesap oluşturulamadı. Lütfen tekrar deneyin.',
    'auth.signup.rateLimit': 'Çok fazla deneme yapıldı. Lütfen birkaç dakika bekleyip tekrar deneyin.',
    'auth.signup.otpExpired': 'E-posta linki geçersiz veya süresi dolmuş. Lütfen yeni bir kayıt denemesi yapın.',
    'auth.signup.emailConfirmationRequired': 'Hesap oluşturuldu! E-postanızı kontrol edip onaylayın, ardından giriş yapın.',
    'auth.signup.companyCreationFailed': 'Şirket profili oluşturulamadı: {message}',
    
    'auth.forgot.title': 'Şifre Sıfırlama',
    'auth.forgot.subtitle': 'E-posta adresinizi girin, şifre sıfırlama bağlantısı gönderilecek',
    'auth.forgot.email': 'E-posta',
    'auth.forgot.submit': 'Bağlantı Gönder',
    'auth.forgot.loading': 'Gönderiliyor...',
    'auth.forgot.back': 'Girişe dön',
    
    'auth.verify.title': 'E-posta Onayı Gerekli',
    'auth.verify.description': 'Hesabınızı kullanmaya başlamak için e-posta adresinizi onaylamanız gerekiyor.',
    'auth.verify.resend': 'E-postayı Tekrar Gönder',
    'auth.verify.sending': 'Gönderiliyor...',
    'auth.verify.check': 'Durumu Kontrol Et',
    'auth.verify.resendSuccess': 'Onay e-postası tekrar gönderildi. Lütfen e-postanızı kontrol edin.',
    'auth.verify.resendError': 'E-posta gönderilemedi. Lütfen tekrar deneyin.',
    'auth.verify.notConfirmed': 'E-posta henüz onaylanmadı. Lütfen e-postanızı kontrol edin.',
    'auth.verify.checkError': 'Durum kontrol edilemedi. Lütfen tekrar deneyin.',
    'auth.verify.backToLogin': 'Giriş sayfasına dön',
    
    // Dashboard
    'dashboard.company.title': 'Şirket Profili',
    'dashboard.company.subtitle': 'Şirket bilgilerinizi yönetin',
    'dashboard.company.details': 'Şirket Detayları',
    'dashboard.company.update': 'Şirket bilgilerinizi ve logonuzu güncelleyin',
    'dashboard.company.logo': 'Şirket Logosu',
    'dashboard.company.logoDesc': 'Kare bir logo yükleyin (önerilen: 400x400px)',
    'dashboard.company.background': 'Arka Plan Görseli',
    'dashboard.company.backgroundDesc': 'Arka plan görseli yükleyin (önerilen: 1920x1080px)',
    'dashboard.company.name': 'Şirket Adı',
    'dashboard.company.phone': 'Telefon',
    'dashboard.company.address': 'Adres',
    'dashboard.company.website': 'Web Sitesi',
    'dashboard.company.save': 'Değişiklikleri Kaydet',
    'dashboard.company.saving': 'Kaydediliyor...',
    'dashboard.company.success': 'Şirket profili başarıyla güncellendi!',
    
    'dashboard.employees.title': 'Çalışanlar',
    'dashboard.employees.subtitle': 'Ekip üyelerinizi yönetin',
    'dashboard.employees.add': 'Çalışan Ekle',
    'dashboard.employees.empty': 'Henüz çalışan yok',
    'dashboard.employees.addFirst': 'İlk Çalışanınızı Ekleyin',
    'dashboard.employees.qr': 'QR Kod',
    'dashboard.employees.edit': 'Düzenle',
    'dashboard.employees.delete': 'Sil',
    'dashboard.employees.appointments': 'Randevular',
    'dashboard.employees.appointmentsFor': 'Randevular -',
    'dashboard.employees.noAppointments': 'Henüz randevu yok',
    'dashboard.employees.customer': 'Müşteri',
    'dashboard.employees.email': 'E-posta',
    'dashboard.employees.phone': 'Telefon',
    'dashboard.employees.notes': 'Notlar',
    'dashboard.employees.confirm': 'Onayla',
    'dashboard.employees.cancel': 'İptal',
    'dashboard.employees.markComplete': 'Tamamlandı İşaretle',
    'dashboard.employees.deleteAppointment': 'Sil',
    'dashboard.employees.deleteConfirm': 'Bu randevuyu silmek istediğinizden emin misiniz?',
    'dashboard.employees.status.pending': 'Beklemede',
    'dashboard.employees.status.confirmed': 'Onaylandı',
    'dashboard.employees.status.cancelled': 'İptal Edildi',
    'dashboard.employees.status.completed': 'Tamamlandı',
    'dashboard.employees.availableHours': 'Randevu İçin Müsait Saatler',
    'dashboard.employees.defaultDuration': 'Varsayılan Süre (dakika)',
    
    // Employee Form
    'employee.form.title': 'Yeni Çalışan Ekle',
    'employee.form.edit': 'Çalışanı Düzenle',
    'employee.form.photo': 'Profil Fotoğrafı',
    'employee.form.firstName': 'Ad',
    'employee.form.lastName': 'Soyad',
    'employee.form.jobTitle': 'İş Unvanı',
    'employee.form.department': 'Departman',
    'employee.form.phone': 'Telefon',
    'employee.form.email': 'E-posta',
    'employee.form.about': 'Hakkında',
    'employee.form.social': 'Sosyal Medya Bağlantıları',
    'employee.form.instagram': 'Instagram',
    'employee.form.linkedin': 'LinkedIn',
    'employee.form.facebook': 'Facebook',
    'employee.form.youtube': 'YouTube',
    'employee.form.whatsapp': 'WhatsApp',
    'employee.form.password': 'Şifre',
    'employee.form.passwordPlaceholder': 'Değiştirmek için yeni şifre girin',
    'employee.form.passwordHint': 'Şifreyi değiştirmek istemiyorsanız boş bırakın',
    'employee.form.cancel': 'İptal',
    'employee.form.save': 'Kaydet',
    
    // Public Profile
    'profile.about': 'Hakkında',
    'profile.connect': 'Bağlantı',
    'profile.companyInfo': 'Şirket Bilgileri',
    'profile.call': 'Ara',
    'profile.email': 'E-posta',
    'profile.whatsapp': 'WhatsApp',
    'profile.notFound': 'Çalışan Bulunamadı',
    'profile.notFoundDesc': 'Aradığınız çalışan profili mevcut değil.',
    'profile.bookAppointment': 'Randevu Al',
    'profile.scheduleAppointment': 'Randevu Planla',
    'profile.scheduleMeeting': 'Toplantı Planla',
    'profile.joinMeeting': 'Toplantıya Katıl',
    'profile.documents': 'Dokümanlar',
    'profile.downloadCV': 'CV İndir',
    'profile.downloadPDF': 'PDF İndir',
    'profile.downloadBrochure': 'Broşür İndir',
    'profile.downloadPresentation': 'Sunum İndir',
    'profile.links': 'Bağlantılar',
    'profile.shareSave': 'Paylaş & Kaydet',
    'profile.scanToSave': 'İletişimi kaydetmek için tara',
    'profile.downloadVCard': 'vCard İndir',
    'profile.shareProfile': 'Profili Paylaş',
    'profile.statistics': 'İstatistikler',
    'profile.views': 'Görüntülenme',
    'profile.clicks': 'Tıklama',
    'profile.appointment.title': 'Randevu Al',
    'profile.appointment.subtitle': 'Randevu tarihi ve saati seçin',
    'profile.appointment.date': 'Tarih',
    'profile.appointment.time': 'Saat',
    'profile.appointment.loadingTimes': 'Müsait saatler yükleniyor...',
    'profile.appointment.noTimes': 'Bu tarih için müsait saat yok',
    'profile.appointment.name': 'Adınız *',
    'profile.appointment.email': 'E-posta Adresiniz *',
    'profile.appointment.phone': 'Telefon Numaranız',
    'profile.appointment.notes': 'Notlar (İsteğe Bağlı)',
    'profile.appointment.cancel': 'İptal',
    'profile.appointment.book': 'Randevu Al',
    'profile.appointment.booking': 'Alınıyor...',
    'profile.appointment.success': 'Randevu başarıyla alındı! Onay e-postası gönderilecek.',
    'profile.appointment.error': 'Randevu alınamadı. Lütfen tekrar deneyin.',
    'profile.appointment.fillAllFields': 'Lütfen tüm gerekli alanları doldurun.',
    'profile.appointment.invalidDateTime': 'Geçersiz tarih veya saat.',
    
    // Common
    'common.logout': 'Çıkış Yap',
    'common.company': 'Şirket',
    'common.employees': 'Çalışanlar',
    'common.calendar': 'Takvim',
    'common.crm': 'Satış Takibi',
    'common.reports': 'Raporlar',
    'common.loading': 'Yükleniyor...',
    
    // Reports
    'reports.subtitle': 'Detaylı raporlar ve analizler',
    'reports.comingSoon': 'Yakında',
    'reports.comingSoonDesc': 'Raporlar özelliği yakında eklenecektir.',
    'reports.comingSoonText': 'Bu sayfada satış takibi, randevu istatistikleri ve diğer detaylı raporlar görüntülenecektir.',
    'reports.noData': 'Veri bulunamadı',
    'reports.crm.total': 'Toplam Lead',
    'reports.crm.sales': 'Satış Yapılan',
    'reports.crm.followUp': 'Takipte',
    'reports.crm.today': 'Bugün Görüşülecek',
    'reports.appointments.total': 'Toplam Randevu',
    'reports.appointments.confirmed': 'Onaylanan',
    'reports.appointments.pending': 'Beklemede',
    'reports.appointments.thisMonth': 'Bu Ay',
    'reports.analytics.views': 'Toplam Görüntülenme',
    'reports.analytics.clicks': 'Toplam Tıklama',
    'reports.analytics.activeEmployees': 'Aktif Çalışanlar',
    'reports.trends.crm': 'CRM Trendi (Son 6 Ay)',
    'reports.trends.crmDesc': 'Aylık lead oluşturma trendi',
    'reports.trends.appointments': 'Randevu Trendi (Son 6 Ay)',
    'reports.trends.appointmentsDesc': 'Aylık randevu oluşturma trendi',
    'reports.employeePerformance': 'Çalışan Performansı',
    'reports.employeePerformanceDesc': 'Çalışanların randevu, lead ve görüntülenme istatistikleri',
    'reports.employee': 'Çalışan',
    'reports.appointments': 'Randevular',
    'reports.leads': 'Leadler',
    'reports.views': 'Görüntülenme',
    'reports.clicks': 'Tıklamalar',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    
    // Calendar
    'calendar.title': 'Takvim',
    'calendar.subtitle': 'Randevularınızı görüntüleyin',
    'calendar.today': 'Bugün',
    'calendar.more': 'daha fazla',
    'calendar.january': 'Ocak',
    'calendar.february': 'Şubat',
    'calendar.march': 'Mart',
    'calendar.april': 'Nisan',
    'calendar.may': 'Mayıs',
    'calendar.june': 'Haziran',
    'calendar.july': 'Temmuz',
    'calendar.august': 'Ağustos',
    'calendar.september': 'Eylül',
    'calendar.october': 'Ekim',
    'calendar.november': 'Kasım',
    'calendar.december': 'Aralık',
    'calendar.sunday': 'Paz',
    'calendar.monday': 'Pzt',
    'calendar.tuesday': 'Sal',
    'calendar.wednesday': 'Çar',
    'calendar.thursday': 'Per',
    'calendar.friday': 'Cum',
    'calendar.saturday': 'Cmt',
    'calendar.sunday.full': 'Pazar',
    'calendar.monday.full': 'Pazartesi',
    'calendar.tuesday.full': 'Salı',
    'calendar.wednesday.full': 'Çarşamba',
    'calendar.thursday.full': 'Perşembe',
    'calendar.friday.full': 'Cuma',
    'calendar.saturday.full': 'Cumartesi',
    'calendar.status.pending': 'Beklemede',
    'calendar.status.confirmed': 'Onaylandı',
    'calendar.status.cancelled': 'İptal Edildi',
    'calendar.status.completed': 'Tamamlandı',
    'calendar.detail.title': 'Randevu Detayları',
    'calendar.detail.subtitle': 'Randevu bilgilerini görüntüleyin',
    'calendar.detail.employee': 'Çalışan',
    'calendar.detail.customer': 'Müşteri',
    'calendar.detail.email': 'E-posta',
    'calendar.detail.phone': 'Telefon',
    'calendar.detail.duration': 'Süre',
    'calendar.detail.minutes': 'dakika',
    'calendar.detail.notes': 'Notlar',
    
    // Employee Dashboard
    'employee.nav.profile': 'Profilim',
    'employee.nav.calendar': 'Takvim',
    'employee.nav.crm': 'Satış Takibi',
    'employee.nav.reports': 'Raporlar',
    'employee.dashboard.title': 'Profilim',
    'employee.dashboard.subtitle': 'Dijital kartvizitinizi görüntüleyin',
    'employee.dashboard.notFound': 'Çalışan bulunamadı',
    'employee.dashboard.qrCode': 'QR Kodunuz',
    'employee.dashboard.qrDescription': 'Bu QR kodu paylaşarak insanların dijital kartvizitinize erişmesini sağlayın',
    'employee.dashboard.share': 'Paylaş',
    
    // Employee Calendar
    'employee.calendar.title': 'Takvimim',
    'employee.calendar.subtitle': 'Randevularınızı görüntüleyin ve yönetin',
    'employee.calendar.addAppointment': 'Randevu Ekle',
    'employee.calendar.detail.title': 'Randevu Detayları',
    'employee.calendar.detail.subtitle': 'Randevu bilgilerini görüntüleyin ve yönetin',
    'employee.calendar.confirm': 'Onayla',
    'employee.calendar.cancel': 'İptal',
    'employee.calendar.markComplete': 'Tamamlandı İşaretle',
    'employee.calendar.delete': 'Sil',
    'employee.calendar.deleteConfirm': 'Bu randevuyu silmek istediğinizden emin misiniz?',
    'employee.calendar.addTitle': 'Yeni Randevu Ekle',
    'employee.calendar.addSubtitle': 'Manuel olarak yeni bir randevu oluşturun',
    'employee.calendar.date': 'Tarih',
    'employee.calendar.time': 'Saat',
    'employee.calendar.add': 'Ekle',
    
    // Employee Credentials
    'employee.credentials.title': 'Çalışan Giriş Bilgileri',
    'employee.credentials.note': 'Bu bilgileri çalışanınızla paylaşın. Şifre bir daha gösterilmeyecektir.',
    'employee.credentials.passwordNotAvailable': 'Şifre güvenlik nedeniyle saklanmıştır. Çalışan şifresini unutursa yeni şifre belirleyebilirsiniz.',
    
    // CRM
    'crm.title': 'Satış Takibi',
    'crm.subtitle': 'Müşteri ve potansiyel kayıtlarınızı yönetin',
    'crm.addLead': 'Yeni Lead Ekle',
    'crm.editLead': 'Lead Düzenle',
    'crm.deleteLead': 'Lead Sil',
    'crm.deleteConfirm': 'Bu lead\'i silmek istediğinizden emin misiniz?',
    'crm.customerName': 'Müşteri Adı / Firma',
    'crm.contactName': 'Yetkili Kişi',
    'crm.phone': 'Telefon',
    'crm.email': 'E-posta',
    'crm.notes': 'Görüşme Notları',
    'crm.followUpDate': 'Takip Tarihi',
    'crm.status': 'Durum',
    'crm.status.new': 'Yeni',
    'crm.status.contacted': 'Görüşüldü',
    'crm.status.sold': 'Satış Yapıldı',
    'crm.status.rejected': 'Reddedildi',
    'crm.status.followUp': 'Takipte',
    'crm.stats.total': 'Toplam Lead',
    'crm.stats.today': 'Bugün Görüşülecek',
    'crm.stats.sales': 'Satış Yapılan',
    'crm.stats.followUp': 'Takipte',
    'crm.empty': 'Henüz lead yok',
    'crm.emptyDesc': 'İlk lead\'inizi ekleyerek başlayın',
    'crm.filter': 'Filtrele',
    'crm.filter.all': 'Tümü',
    'crm.save': 'Kaydet',
    'crm.cancel': 'İptal',
    'crm.created': 'Oluşturulma',
    'crm.updated': 'Güncellenme',
    'crm.view.list': 'Liste',
    'crm.view.kanban': 'Kanban',
    'crm.edit': 'Düzenle',
    'crm.assignedEmployee': 'İlgilenen Çalışan',
    'crm.noEmployee': 'Çalışan Seçilmedi',
  },
  en: {
    // Auth
    'auth.login.title': 'Sign In',
    'auth.login.subtitle': 'Sign in to your company account',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.submit': 'Sign In',
    'auth.login.loading': 'Signing in...',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.signup': 'Sign up',
    'auth.login.employeeLogin': 'Employee Login',
    'auth.login.error': 'Invalid email or password',
    'auth.login.errorGeneric': 'An error occurred. Please try again.',
    
    'auth.employeeLogin.subtitle': 'Sign in to your employee account',
    'auth.employeeLogin.username': 'Username',
    'auth.employeeLogin.password': 'Password',
    'auth.employeeLogin.submit': 'Sign In',
    'auth.employeeLogin.loading': 'Signing in...',
    'auth.employeeLogin.invalid': 'Invalid username or password',
    'auth.employeeLogin.companyLogin': 'Company Login',
    'auth.employeeLogin.backToCompany': 'Back to company login',
    
    'auth.signup.title': 'Sign Up',
    'auth.signup.subtitle': 'Create your company account',
    'auth.signup.companyName': 'Company Name',
    'auth.signup.email': 'Email',
    'auth.signup.password': 'Password',
    'auth.signup.language': 'Language',
    'auth.signup.submit': 'Sign Up',
    'auth.signup.loading': 'Creating account...',
    'auth.signup.hasAccount': 'Already have an account?',
    'auth.signup.signin': 'Sign in',
    'auth.signup.success': 'Account created successfully! Redirecting...',
    'auth.signup.error': 'Failed to create account. Please try again.',
    'auth.signup.rateLimit': 'Too many attempts. Please wait a few minutes and try again.',
    'auth.signup.otpExpired': 'Email link is invalid or has expired. Please try signing up again.',
    'auth.signup.emailConfirmationRequired': 'Account created! Please check your email to confirm, then log in.',
    'auth.signup.companyCreationFailed': 'Failed to create company profile: {message}',
    
    'auth.forgot.title': 'Reset Password',
    'auth.forgot.subtitle': 'Enter your email to receive a password reset link',
    'auth.forgot.email': 'Email',
    'auth.forgot.submit': 'Send Reset Link',
    'auth.forgot.loading': 'Sending...',
    'auth.forgot.back': 'Back to login',
    
    'auth.verify.title': 'Email Verification Required',
    'auth.verify.description': 'You need to verify your email address to start using your account.',
    'auth.verify.resend': 'Resend Email',
    'auth.verify.sending': 'Sending...',
    'auth.verify.check': 'Check Status',
    'auth.verify.resendSuccess': 'Verification email has been resent. Please check your email.',
    'auth.verify.resendError': 'Failed to send email. Please try again.',
    'auth.verify.notConfirmed': 'Email has not been confirmed yet. Please check your email.',
    'auth.verify.checkError': 'Failed to check status. Please try again.',
    'auth.verify.backToLogin': 'Back to login',
    
    // Dashboard
    'dashboard.company.title': 'Company Profile',
    'dashboard.company.subtitle': 'Manage your company information',
    'dashboard.company.details': 'Company Details',
    'dashboard.company.update': 'Update your company information and logo',
    'dashboard.company.logo': 'Company Logo',
    'dashboard.company.logoDesc': 'Upload a square logo (recommended: 400x400px)',
    'dashboard.company.background': 'Background Image',
    'dashboard.company.backgroundDesc': 'Upload a background image (recommended: 1920x1080px)',
    'dashboard.company.name': 'Company Name',
    'dashboard.company.phone': 'Phone',
    'dashboard.company.address': 'Address',
    'dashboard.company.website': 'Website',
    'dashboard.company.save': 'Save Changes',
    'dashboard.company.saving': 'Saving...',
    'dashboard.company.success': 'Company profile updated successfully!',
    
    'dashboard.employees.title': 'Employees',
    'dashboard.employees.subtitle': 'Manage your team members',
    'dashboard.employees.add': 'Add Employee',
    'dashboard.employees.empty': 'No employees yet',
    'dashboard.employees.addFirst': 'Add Your First Employee',
    'dashboard.employees.qr': 'QR Code',
    'dashboard.employees.edit': 'Edit',
    'dashboard.employees.delete': 'Delete',
    'dashboard.employees.appointments': 'Appointments',
    'dashboard.employees.appointmentsFor': 'Appointments for',
    'dashboard.employees.noAppointments': 'No appointments yet',
    'dashboard.employees.customer': 'Customer',
    'dashboard.employees.email': 'Email',
    'dashboard.employees.phone': 'Phone',
    'dashboard.employees.notes': 'Notes',
    'dashboard.employees.confirm': 'Confirm',
    'dashboard.employees.cancel': 'Cancel',
    'dashboard.employees.markComplete': 'Mark Complete',
    'dashboard.employees.deleteAppointment': 'Delete',
    'dashboard.employees.deleteConfirm': 'Are you sure you want to delete this appointment?',
    'dashboard.employees.status.pending': 'Pending',
    'dashboard.employees.status.confirmed': 'Confirmed',
    'dashboard.employees.status.cancelled': 'Cancelled',
    'dashboard.employees.status.completed': 'Completed',
    'dashboard.employees.availableHours': 'Available Hours for Appointments',
    'dashboard.employees.defaultDuration': 'Default Duration (minutes)',
    
    // Employee Form
    'employee.form.title': 'Add New Employee',
    'employee.form.edit': 'Edit Employee',
    'employee.form.photo': 'Profile Photo',
    'employee.form.firstName': 'First Name',
    'employee.form.lastName': 'Last Name',
    'employee.form.jobTitle': 'Job Title',
    'employee.form.department': 'Department',
    'employee.form.phone': 'Phone',
    'employee.form.email': 'Email',
    'employee.form.about': 'About',
    'employee.form.social': 'Social Media Links',
    'employee.form.instagram': 'Instagram',
    'employee.form.linkedin': 'LinkedIn',
    'employee.form.facebook': 'Facebook',
    'employee.form.youtube': 'YouTube',
    'employee.form.whatsapp': 'WhatsApp',
    'employee.form.password': 'Password',
    'employee.form.passwordPlaceholder': 'Enter new password to change',
    'employee.form.passwordHint': "Leave blank if you don't want to change the password",
    'employee.form.cancel': 'Cancel',
    'employee.form.save': 'Save',
    
    // Public Profile
    'profile.about': 'About',
    'profile.connect': 'Connect',
    'profile.companyInfo': 'Company Information',
    'profile.call': 'Call',
    'profile.email': 'Email',
    'profile.whatsapp': 'WhatsApp',
    'profile.notFound': 'Employee Not Found',
    'profile.notFoundDesc': "The employee profile you're looking for doesn't exist.",
    'profile.bookAppointment': 'Book Appointment',
    'profile.scheduleAppointment': 'Schedule Appointment',
    'profile.scheduleMeeting': 'Schedule Meeting',
    'profile.joinMeeting': 'Join Meeting',
    'profile.documents': 'Documents',
    'profile.downloadCV': 'Download CV',
    'profile.downloadPDF': 'Download PDF',
    'profile.downloadBrochure': 'Download Brochure',
    'profile.downloadPresentation': 'Download Presentation',
    'profile.links': 'Links',
    'profile.shareSave': 'Share & Save',
    'profile.scanToSave': 'Scan to save contact',
    'profile.downloadVCard': 'Download vCard',
    'profile.shareProfile': 'Share Profile',
    'profile.statistics': 'Statistics',
    'profile.views': 'Views',
    'profile.clicks': 'Clicks',
    'profile.appointment.title': 'Book Appointment',
    'profile.appointment.subtitle': 'Select a date and time for your appointment',
    'profile.appointment.date': 'Date',
    'profile.appointment.time': 'Time',
    'profile.appointment.loadingTimes': 'Loading available times...',
    'profile.appointment.noTimes': 'No available times for this date',
    'profile.appointment.name': 'Your Name *',
    'profile.appointment.email': 'Your Email *',
    'profile.appointment.phone': 'Your Phone',
    'profile.appointment.notes': 'Notes (Optional)',
    'profile.appointment.cancel': 'Cancel',
    'profile.appointment.book': 'Book Appointment',
    'profile.appointment.booking': 'Booking...',
    'profile.appointment.success': 'Appointment booked successfully! You will receive a confirmation email.',
    'profile.appointment.error': 'Failed to book appointment. Please try again.',
    'profile.appointment.fillAllFields': 'Please fill in all required fields.',
    'profile.appointment.invalidDateTime': 'Invalid date or time.',
    
    // Common
    'common.logout': 'Logout',
    'common.company': 'Company',
    'common.employees': 'Employees',
    'common.calendar': 'Calendar',
    'common.crm': 'Sales Tracking',
    'common.reports': 'Reports',
    'common.loading': 'Loading...',
    
    // Reports
    'reports.subtitle': 'Detailed reports and analytics',
    'reports.comingSoon': 'Coming Soon',
    'reports.comingSoonDesc': 'Reports feature will be added soon.',
    'reports.comingSoonText': 'This page will display sales tracking, appointment statistics, and other detailed reports.',
    'reports.noData': 'No data found',
    'reports.crm.total': 'Total Leads',
    'reports.crm.sales': 'Sales Completed',
    'reports.crm.followUp': 'In Follow-up',
    'reports.crm.today': 'Today\'s Follow-ups',
    'reports.appointments.total': 'Total Appointments',
    'reports.appointments.confirmed': 'Confirmed',
    'reports.appointments.pending': 'Pending',
    'reports.appointments.thisMonth': 'This Month',
    'reports.analytics.views': 'Total Views',
    'reports.analytics.clicks': 'Total Clicks',
    'reports.analytics.activeEmployees': 'Active Employees',
    'reports.trends.crm': 'CRM Trend (Last 6 Months)',
    'reports.trends.crmDesc': 'Monthly lead creation trend',
    'reports.trends.appointments': 'Appointment Trend (Last 6 Months)',
    'reports.trends.appointmentsDesc': 'Monthly appointment creation trend',
    'reports.employeePerformance': 'Employee Performance',
    'reports.employeePerformanceDesc': 'Employee appointment, lead, and view statistics',
    'reports.employee': 'Employee',
    'reports.appointments': 'Appointments',
    'reports.leads': 'Leads',
    'reports.views': 'Views',
    'reports.clicks': 'Clicks',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Calendar
    'calendar.title': 'Calendar',
    'calendar.subtitle': 'View your appointments',
    'calendar.today': 'Today',
    'calendar.more': 'more',
    'calendar.january': 'January',
    'calendar.february': 'February',
    'calendar.march': 'March',
    'calendar.april': 'April',
    'calendar.may': 'May',
    'calendar.june': 'June',
    'calendar.july': 'July',
    'calendar.august': 'August',
    'calendar.september': 'September',
    'calendar.october': 'October',
    'calendar.november': 'November',
    'calendar.december': 'December',
    'calendar.sunday': 'Sun',
    'calendar.monday': 'Mon',
    'calendar.tuesday': 'Tue',
    'calendar.wednesday': 'Wed',
    'calendar.thursday': 'Thu',
    'calendar.friday': 'Fri',
    'calendar.saturday': 'Sat',
    'calendar.sunday.full': 'Sunday',
    'calendar.monday.full': 'Monday',
    'calendar.tuesday.full': 'Tuesday',
    'calendar.wednesday.full': 'Wednesday',
    'calendar.thursday.full': 'Thursday',
    'calendar.friday.full': 'Friday',
    'calendar.saturday.full': 'Saturday',
    'calendar.status.pending': 'Pending',
    'calendar.status.confirmed': 'Confirmed',
    'calendar.status.cancelled': 'Cancelled',
    'calendar.status.completed': 'Completed',
    'calendar.detail.title': 'Appointment Details',
    'calendar.detail.subtitle': 'View appointment information',
    'calendar.detail.employee': 'Employee',
    'calendar.detail.customer': 'Customer',
    'calendar.detail.email': 'Email',
    'calendar.detail.phone': 'Phone',
    'calendar.detail.duration': 'Duration',
    'calendar.detail.minutes': 'minutes',
    'calendar.detail.notes': 'Notes',
    
    // Employee Dashboard
    'employee.nav.profile': 'My Profile',
    'employee.nav.calendar': 'Calendar',
    'employee.nav.crm': 'Sales Tracking',
    'employee.nav.reports': 'Reports',
    'employee.dashboard.title': 'My Profile',
    'employee.dashboard.subtitle': 'View your digital business card',
    'employee.dashboard.notFound': 'Employee not found',
    'employee.dashboard.qrCode': 'Your QR Code',
    'employee.dashboard.qrDescription': 'Share this QR code to let people access your digital business card',
    'employee.dashboard.share': 'Share',
    
    // Employee Calendar
    'employee.calendar.title': 'My Calendar',
    'employee.calendar.subtitle': 'View and manage your appointments',
    'employee.calendar.addAppointment': 'Add Appointment',
    'employee.calendar.detail.title': 'Appointment Details',
    'employee.calendar.detail.subtitle': 'View and manage appointment details',
    'employee.calendar.confirm': 'Confirm',
    'employee.calendar.cancel': 'Cancel',
    'employee.calendar.markComplete': 'Mark Complete',
    'employee.calendar.delete': 'Delete',
    'employee.calendar.deleteConfirm': 'Are you sure you want to delete this appointment?',
    'employee.calendar.addTitle': 'Add New Appointment',
    'employee.calendar.addSubtitle': 'Create a new appointment manually',
    'employee.calendar.date': 'Date',
    'employee.calendar.time': 'Time',
    'employee.calendar.add': 'Add',
    
    // Employee Credentials
    'employee.credentials.title': 'Employee Login Credentials',
    'employee.credentials.note': 'Share these credentials with your employee. The password will not be shown again.',
    'employee.credentials.passwordNotAvailable': 'Password is stored securely. If employee forgets password, you can set a new one.',
    
    // CRM
    'crm.title': 'Sales Tracking',
    'crm.subtitle': 'Manage your customer and potential leads',
    'crm.addLead': 'Add New Lead',
    'crm.editLead': 'Edit Lead',
    'crm.deleteLead': 'Delete Lead',
    'crm.deleteConfirm': 'Are you sure you want to delete this lead?',
    'crm.customerName': 'Customer Name / Company',
    'crm.contactName': 'Contact Person',
    'crm.phone': 'Phone',
    'crm.email': 'Email',
    'crm.notes': 'Meeting Notes',
    'crm.followUpDate': 'Follow-up Date',
    'crm.status': 'Status',
    'crm.status.new': 'New',
    'crm.status.contacted': 'Contacted',
    'crm.status.sold': 'Sale Completed',
    'crm.status.rejected': 'Rejected',
    'crm.status.followUp': 'Follow-up',
    'crm.stats.total': 'Total Leads',
    'crm.stats.today': 'Today\'s Follow-ups',
    'crm.stats.sales': 'Sales Completed',
    'crm.stats.followUp': 'In Follow-up',
    'crm.empty': 'No leads yet',
    'crm.emptyDesc': 'Start by adding your first lead',
    'crm.filter': 'Filter',
    'crm.filter.all': 'All',
    'crm.save': 'Save',
    'crm.cancel': 'Cancel',
    'crm.created': 'Created',
    'crm.updated': 'Updated',
    'crm.view.list': 'List',
    'crm.view.kanban': 'Kanban',
    'crm.edit': 'Edit',
    'crm.assignedEmployee': 'Assigned Employee',
    'crm.noEmployee': 'No Employee Selected',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const storedLang = localStorage.getItem('appLanguage')
    return (storedLang === 'tr' || storedLang === 'en') ? storedLang : 'en'
  })

  useEffect(() => {
    localStorage.setItem('appLanguage', language)
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    // Mark that user manually changed language
    localStorage.setItem('languageManuallyChanged', 'true')
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.tr] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

